language: csharp
dist: trusty
mono: none
dotnet: 2.1.401
install:
- dotnet restore
script:
- dotnet build -c Release
- dotnet test src/Kritner.SolarProjection.Tests/Kritner.SolarProjection.Tests.csproj -c Release
